---
roles:
  # Install a role from Ansible Galaxy.
  - src: https://github.com/florianutz/ubuntu2004_cis.git
  - src: https://github.com/trallnag/ansible-role-endlessh.git
  - src: https://github.com/siw36/ansible-steamcmd.git
  - src: https://github.com/geerlingguy/ansible-role-docker
  - src: https://github.com/geerlingguy/ansible-role-pip
  - src: https://github.com/Brandon1811/ansible-role-assetto-corsa-server

collections:
  - name: community.docker
